/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_FILEMONITOR
(
	FILEMONITORINFOID	VARCHAR(128)	NOT NULL	UNIQUE,
	WORKINGGROUP	VARCHAR(128)	NOT NULL,
	RESOURCESTATUS	VARCHAR(10)	NOT NULL,
	TARGETNODEID	VARCHAR(128)	NOT NULL,
	TARGETINFO_TARGETTYPE	VARCHAR(128)	NOT NULL,
	TARGETINFO_TARGETID	VARCHAR(128)	NOT NULL,
	TARGETINFO_SUBTARGETID	VARCHAR(128)	NOT NULL,
	TARGETFILENAME	VARCHAR(256)	NOT NULL,
	TARGETDIR	VARCHAR(256)	NOT NULL,
	NOTES	VARCHAR(1000)	NOT NULL,
	PRIMARY KEY (FILEMONITORINFOID),
	FOREIGN KEY (WORKINGGROUP) REFERENCES APEX_WORKINGGROUP(WORKINGGROUP)
)	WITHOUT OIDS;