/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_IDOC
(
	IDOCCOOPERATIONCODE	VARCHAR(128)	NOT NULL	UNIQUE,
	R3IDOCTYPE	VARCHAR(30)	NOT NULL,
	R3MESSAGETYPE	VARCHAR(30)	NOT NULL,
	WORKINGGROUP	VARCHAR(128)	NOT NULL,
	USERID	VARCHAR(128)	NOT NULL,
	NOTES	VARCHAR(1000)	NOT NULL,
	IDOCANYCONVDEF_CONVDEFFILE	VARCHAR(128)	NOT NULL,
	FILEID	VARCHAR(128)	NOT NULL,
	PRIMARY KEY (IDOCCOOPERATIONCODE),
	FOREIGN KEY (WORKINGGROUP) REFERENCES APEX_WORKINGGROUP(WORKINGGROUP)
)	WITHOUT OIDS;