/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_FILE
(
	USERID	VARCHAR(128)	NOT NULL,
	FILEID	VARCHAR(128)	NOT NULL	UNIQUE,
	PROTOCOLID	VARCHAR(30)	NOT NULL,
	WORKINGGROUP	VARCHAR(128)	NOT NULL,
	DATASTORE	VARCHAR(128)	NOT NULL,
	RESOURCESTATUS	VARCHAR(10)	NOT NULL,
	LENDABLE	BOOLEAN,
	TRANSFERDIRECTION	VARCHAR(10)	NOT NULL,
	NOTES	VARCHAR(1000)	NOT NULL,
	NORMALENDTARGET_TARGETTYPE	VARCHAR(50)	NOT NULL,
	NORMALENDTARGET_TARGETID	VARCHAR(128)	NOT NULL,
	NORMALENDTARGET_SUBTARGETID	VARCHAR(128)	NOT NULL,
	ERRORENDTARGET_TARGETTYPE	VARCHAR(20)	NOT NULL,
	ERRORENDTARGET_TARGETID	VARCHAR(128)	NOT NULL,
	ERRORENDTARGET_SUBTARGETID	VARCHAR(128)	NOT NULL,
	CONNECTIONDIRECTION	VARCHAR(10)	NOT NULL,
	PRIMARY KEY (FILEID),
	FOREIGN KEY (USERID) REFERENCES APEX_USER(USERID),
	FOREIGN KEY (WORKINGGROUP) REFERENCES APEX_WORKINGGROUP(WORKINGGROUP)
)	WITHOUT OIDS;