/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_WORKINGGROUP
(
	WORKINGGROUP	VARCHAR(128)	NOT NULL	UNIQUE,
	RESOURCESTATUS	VARCHAR(10)	NOT NULL,
	NOTES	VARCHAR(1000)	NOT NULL,
	PRIMARY KEY (WORKINGGROUP)
)	WITHOUT OIDS;