/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_COMM_TASK
(
	TASKID	VARCHAR(23)	NOT NULL	UNIQUE,
	WORKINGGROUP	VARCHAR(128)	NOT NULL,
	TARGETTYPE	VARCHAR(5)	NOT NULL,
	TARGETID	VARCHAR(128)	NOT NULL,
	SUBTARGETID	VARCHAR(128)	NOT NULL,
	STATUS	VARCHAR(10)	NOT NULL,
	STARTPLANDATETIME	VARCHAR(23)	NOT NULL,
	TASKSTARTDATETIME	VARCHAR(23)	NOT NULL,
	TASKENDDATETIME	VARCHAR(23)	NOT NULL,
	PORTGROUP	VARCHAR(128)	NOT NULL,
	PORTID	VARCHAR(128)	NOT NULL,
	OUTPUTPARAMETERS_COMM_TRANSFER_DIRECTION	VARCHAR(30)	NOT NULL,
	OUTPUTPARAMETERS_COMM_PROTOCOL	VARCHAR(30)	NOT NULL,
	OUTPUTPARAMETERS_COMM_BYTE_COUNT	NUMERIC	NOT NULL,
	OUTPUTPARAMETERS_COMM_CONNECTION_DIRECTION	VARCHAR(30)	NOT NULL,
	PRIMARY KEY (TASKID)
)	WITHOUT OIDS;