/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_SCHEDULE
(
	SCHEDULEID	VARCHAR(128)	NOT NULL	UNIQUE,
	WORKINGGROUP	VARCHAR(128)	NOT NULL,
	RESOURCESTATUS	VARCHAR(10)	NOT NULL,
	TARGETINFO_TARGETTYPE	VARCHAR(10)	NOT NULL,
	TARGETINFO_TARGETID	VARCHAR(128)	NOT NULL,
	TARGETINFO_SUBTARGETID	VARCHAR(128)	NOT NULL,
	SCHEDULERTYPE	VARCHAR(50)	NOT NULL,
	NOTES	VARCHAR(1000)	NOT NULL,
	PRIMARY KEY (SCHEDULEID),
	FOREIGN KEY (WORKINGGROUP) REFERENCES APEX_WORKINGGROUP(WORKINGGROUP)
)	WITHOUT OIDS;