/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_GLOBALMERGEPOINT
(
	GLOBALMERGEPOINTID	VARCHAR(128)	NOT NULL	UNIQUE,
	WORKINGGROUP	VARCHAR(128)	NOT NULL,
	PORTGROUP	VARCHAR(128)	NOT NULL,
	DATASTORE	VARCHAR(128)	NOT NULL,
	RESOURCESTATUS	VARCHAR(10)	NOT NULL,
	LENDABLE	BOOLEAN,
	NOTES	VARCHAR(1000)	NOT NULL,
	GLOBALMERGEINFO_CLOSEENDTARGET_TARGETTYPE	VARCHAR(5)	NOT NULL,
	GLOBALMERGEINFO_CLOSEENDTARGET_TARGETID	VARCHAR(128)	NOT NULL,
	GLOBALMERGEINFO_CLOSEENDTARGET_SUBTARGETID	VARCHAR(128)	NOT NULL,
	PRIMARY KEY (GLOBALMERGEPOINTID),
	FOREIGN KEY (WORKINGGROUP) REFERENCES APEX_WORKINGGROUP(WORKINGGROUP)
)	WITHOUT OIDS;