/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_COMMPORTGROUP
(
	PORTGROUP	VARCHAR(128)	NOT NULL	UNIQUE,
	WORKINGGROUP	VARCHAR(128)	NOT NULL,
	LENDABLE	BOOLEAN,
	COMPORTTYPE	VARCHAR(10)	NOT NULL,
	PRIMARY KEY (PORTGROUP),
	FOREIGN KEY (WORKINGGROUP) REFERENCES APEX_WORKINGGROUP(WORKINGGROUP)
)	WITHOUT OIDS;