/* CREATE TABLE 2020/09/09 */

CREATE	TABLE	APEX_USER
(
	USERID	VARCHAR(128)	NOT NULL	UNIQUE,
	PROTOCOLID	VARCHAR(30)	NOT NULL,
	WORKINGGROUP	VARCHAR(128)	NOT NULL,
	PORTGROUP	VARCHAR(128)	NOT NULL,
	DATASTORE	VARCHAR(128)	NOT NULL,
	RESOURCESTATUS	VARCHAR(10)	NOT NULL,
	LENDABLE	BOOLEAN,
	NOTES	VARCHAR(1000)	NOT NULL,
	PRIMARY KEY (USERID),
	FOREIGN KEY (WORKINGGROUP) REFERENCES APEX_WORKINGGROUP(WORKINGGROUP)
)	WITHOUT OIDS;